/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17448556
 */
public class EmployeeGUI extends javax.swing.JFrame {
        
    /**
     * Creates new form EmployeeGUI
     */
    Employee e;
    /*Employee log[] = new Employee[100];
    int count;*/
    ArrayList<Employee> log = new ArrayList();
    String name;
    String id;
    String dob;
    double salary;
    double rate;
    double hours;

    public EmployeeGUI() {
        initComponents();
        rateLbl.setVisible(false);
        rateTxt.setVisible(false);
        hoursLbl.setVisible(false);
        hoursTxt.setVisible(false);
        salaryLbl.setVisible(false);
        salaryTxt.setVisible(false);
        ///count = 0;
        readFromFile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        rateLbl = new javax.swing.JLabel();
        rateTxt = new javax.swing.JTextField();
        hoursLbl = new javax.swing.JLabel();
        hoursTxt = new javax.swing.JTextField();
        printBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();
        floorStaffBtn = new javax.swing.JButton();
        managerBtn = new javax.swing.JButton();
        salaryLbl = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employeeLbl.setText("Employee Application");

        nameLbl.setText("Name");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        idLbl.setText("ID");

        dobLbl.setText("DOB");

        rateLbl.setText("Rate");

        hoursLbl.setText("Hours");

        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        payBtn.setText("Compute Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        floorStaffBtn.setText("Floorstaff");
        floorStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorStaffBtnActionPerformed(evt);
            }
        });

        managerBtn.setText("Manager");
        managerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBtnActionPerformed(evt);
            }
        });

        salaryLbl.setText("Salary");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display Employees");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(employeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(hoursLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(hoursTxt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idLbl)
                                            .addComponent(dobLbl)
                                            .addComponent(rateLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameTxt)
                                            .addComponent(dobTxt)
                                            .addComponent(rateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(idTxt))))
                                .addGap(18, 18, 18)
                                .addComponent(salaryLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(floorStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(managerBtn)
                                    .addComponent(payBtn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayBtn)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(employeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryLbl)
                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLbl)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLbl)
                    .addComponent(rateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLbl)
                    .addComponent(hoursTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(payBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorStaffBtn)
                    .addComponent(managerBtn)
                    .addComponent(displayBtn))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void floorStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorStaffBtnActionPerformed
        // TODO add your handling code here:
        rateLbl.setVisible(true);
        rateTxt.setVisible(true);
        hoursLbl.setVisible(true);
        hoursTxt.setVisible(true);
        salaryLbl.setVisible(false);
        salaryTxt.setVisible(false);

        e = new FloorStaff();
    }//GEN-LAST:event_floorStaffBtnActionPerformed

    private void managerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBtnActionPerformed
        // TODO add your handling code here:
        rateLbl.setVisible(false);
        rateTxt.setVisible(false);
        hoursLbl.setVisible(false);
        hoursTxt.setVisible(false);
        salaryLbl.setVisible(true);
        salaryTxt.setVisible(true);
        e = new Manager();

    }//GEN-LAST:event_managerBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        if (e instanceof FloorStaff) {
            String name = nameTxt.getText();
            String id = idTxt.getText();
            String dob = dobTxt.getText();
            double rate = Double.parseDouble(rateTxt.getText());
            double hours = Double.parseDouble(hoursTxt.getText());

            e.setName(name);
            e.setDob(dob);
            e.setId(id);
            ((FloorStaff) e).setRate(rate);
            ((FloorStaff) e).setHours(hours);

            String output = e.printDetails();
            JOptionPane.showMessageDialog(null, output);
        }
        if (e instanceof Manager) {
            String name = nameTxt.getText();
            String id = idTxt.getText();
            String dob = dobTxt.getText();
            double salary = Double.parseDouble(salaryTxt.getText());

            e.setName(name);
            e.setDob(dob);
            e.setId(id);
            ((Manager) e).setSalary(salary);
            String output = e.printDetails();
            JOptionPane.showMessageDialog(null, output);
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:

        if (e instanceof Manager) {
            e = new Manager();
            e.setName(nameTxt.getText());
            e.setDob(dobTxt.getText());
            e.setId(idTxt.getText());
            ((Manager) e).setSalary(Double.parseDouble(salaryTxt.getText()));
            e.computeWPay();
            JOptionPane.showMessageDialog(null, ((Manager) e).getwPay());

        }
        if (e instanceof FloorStaff) {
            e = new FloorStaff();
            e.setName(nameTxt.getText());
            e.setDob(dobTxt.getText());
            e.setId(idTxt.getText());
            ((FloorStaff) e).setHours(Double.parseDouble(hoursTxt.getText()));
            ((FloorStaff) e).setRate(Double.parseDouble(rateTxt.getText()));
            e.computeWPay();
            JOptionPane.showMessageDialog(null, ((FloorStaff) e).getwPay());
        }
    }//GEN-LAST:event_payBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        if (e instanceof Manager) {
            name = nameTxt.getText();
            id = dobTxt.getText();
            dob = dobTxt.getText();
            salary = Double.parseDouble(salaryTxt.getText());

            e.setName(name);
            e.setId(id);
            e.setDob(dob);
            ((Manager) e).setSalary(salary);

            log.add(e);
        }
        if (e instanceof FloorStaff) {
            name = nameTxt.getText();
            id = dobTxt.getText();
            dob = dobTxt.getText();
            rate = Double.parseDouble(rateTxt.getText());
            hours = Double.parseDouble(hoursTxt.getText());

            e.setName(name);
            e.setId(id);
            e.setDob(dob);
            ((FloorStaff) e).setRate(rate);
            ((FloorStaff) e).setHours(hours);
            log.add(e);
        }
        writeToFile();
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < log.size(); i++) {
            JOptionPane.showMessageDialog(null, log.get(i).printDetails());
        }
    }//GEN-LAST:event_displayBtnActionPerformed
    public void writeToFile() {
        try {
            File f = new File("output.dat");
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(log);
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    public void readFromFile(){
        try{
              File f = new File("output.dat");
              FileInputStream fStream = new FileInputStream(f);
              ObjectInputStream oStream = new ObjectInputStream(fStream);
              log= (ArrayList<Employee>)oStream.readObject();
              oStream.close();
              
        }
        catch(IOException | ClassNotFoundException ex)
        {
        System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel employeeLbl;
    private javax.swing.JButton floorStaffBtn;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField hoursTxt;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton managerBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton payBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTxt;
    private javax.swing.JLabel salaryLbl;
    private javax.swing.JTextField salaryTxt;
    // End of variables declaration//GEN-END:variables
}
