/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopProjectFinal;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x18114245
 */
public class payrolGUI extends javax.swing.JFrame {

    // declare variables in the PAYROL class
    String firstname, surname;
    String address, dob, id;
    String ppsnumber;
    Double usc, netpay, healthInsurance, taxCredit, unionSubs, prsi, overTime;
    Double gross, hours, rate;
    int count = 0; //set initial COUNT value to zero

    payrol p; //MAKE INSTANT OF PAYROL CLASS
    public ArrayList<hr> aList = new ArrayList(); //declare AND CREATE ARRAYLISTL

    /**
     * Creates new form payrolGUI
     */
    public payrolGUI() {
        initComponents();
        //SET GROSS,PRSI,USC,NETPAY AND PAY ( TEXTFIELD AND LABEL) TO INVISIBLE
        grossLbl.setVisible(false);
        grossTF.setVisible(false);
        prsilbl.setVisible(false);
        prsiTF.setVisible(false);

        usclbl.setVisible(false);
        uscTF.setVisible(false);

        netpaylbl.setVisible(false);
        netpayTF.setVisible(false);
        paylbl.setVisible(false);
        payTF.setVisible(false);

         readFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnameLbl = new javax.swing.JLabel();
        surnameLbl = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        ppsnumberLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        hoursLbl = new javax.swing.JLabel();
        rateLbl = new javax.swing.JLabel();
        overtimeLbl = new javax.swing.JLabel();
        grossLbl = new javax.swing.JLabel();
        prsilbl = new javax.swing.JLabel();
        netpaylbl = new javax.swing.JLabel();
        taxCreditLbl = new javax.swing.JLabel();
        usclbl = new javax.swing.JLabel();
        firstname1TF = new javax.swing.JTextField();
        surname1TF = new javax.swing.JTextField();
        id1TF = new javax.swing.JTextField();
        dob1TF = new javax.swing.JTextField();
        ppsnumber1TF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        overtimeTF = new javax.swing.JTextField();
        grossTF = new javax.swing.JTextField();
        prsiTF = new javax.swing.JTextField();
        netpayTF = new javax.swing.JTextField();
        taxCreditTF = new javax.swing.JTextField();
        uscTF = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        viewAddedDetails = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        search = new javax.swing.JButton();
        viewcalculations = new javax.swing.JButton();
        add = new javax.swing.JButton();
        help = new javax.swing.JButton();
        paylbl = new javax.swing.JLabel();
        payTF = new javax.swing.JTextField();
        healthInsuranceLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        healthInsuranceTF = new javax.swing.JTextField();
        unionSubsTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstnameLbl.setText("firstname");

        surnameLbl.setText("surname");

        idlbl.setText("id");

        dobLbl.setText("dob");

        ppsnumberLbl.setText("pps number");

        addressLbl.setText("adress");

        hoursLbl.setText("hours");

        rateLbl.setText("rate");

        overtimeLbl.setText("overtime");

        grossLbl.setText("gross");

        prsilbl.setText("PRSI");

        netpaylbl.setText("netpay");

        taxCreditLbl.setText("tax credit");

        usclbl.setText("USC");

        ppsnumber1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppsnumber1TFActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        viewAddedDetails.setText("viewAddedDetails");
        viewAddedDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddedDetailsActionPerformed(evt);
            }
        });

        calculate.setText("view stored payslip");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 255, 102));
        Clear.setText("Clear txtField before adding new payslips");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        search.setText("search payslip");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        viewcalculations.setText("check standard tax rates in ireland ");
        viewcalculations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcalculationsActionPerformed(evt);
            }
        });

        add.setText("add new payslip");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        help.setBackground(new java.awt.Color(153, 255, 204));
        help.setText("help?");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        paylbl.setText("pay");

        healthInsuranceLbl.setText("health insurance");

        jLabel2.setText("union subs");

        unionSubsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unionSubsTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ppsnumberLbl)
                                    .addComponent(addressLbl)
                                    .addComponent(hoursLbl)
                                    .addComponent(rateLbl)
                                    .addComponent(overtimeLbl)
                                    .addComponent(grossLbl)
                                    .addComponent(prsilbl)
                                    .addComponent(netpaylbl)
                                    .addComponent(taxCreditLbl)
                                    .addComponent(usclbl))
                                .addGap(12, 124, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(firstnameLbl)
                                .addGap(129, 129, 129))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(surnameLbl)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Clear))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ppsnumber1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(160, 160, 160)
                                .addComponent(calculate))
                            .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(overtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(add))
                            .addComponent(grossTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prsiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(unionSubsTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(healthInsuranceTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taxCreditTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netpayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uscTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payTF, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(search))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(viewcalculations))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstname1TF, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(surname1TF)
                                    .addComponent(id1TF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dob1TF, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(269, 269, 269)
                                .addComponent(help)))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(healthInsuranceLbl)
                            .addComponent(paylbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(logout))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dobLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewAddedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLbl)
                    .addComponent(firstname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout)
                    .addComponent(help))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl)
                    .addComponent(id1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAddedDetails))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLbl)
                    .addComponent(dob1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppsnumberLbl)
                    .addComponent(ppsnumber1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addressLbl)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLbl)
                    .addComponent(Clear)
                    .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLbl)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overtimeLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add)
                        .addComponent(overtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossLbl)
                    .addComponent(grossTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prsilbl)
                    .addComponent(prsiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netpaylbl)
                    .addComponent(netpayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxCreditLbl)
                    .addComponent(taxCreditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usclbl)
                    .addComponent(uscTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paylbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewcalculations)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthInsuranceLbl)
                    .addComponent(healthInsuranceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(unionSubsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        //SET GROSS,PRSI,USC,NETPAY AND PAY ( TEXTFIELD AND LABEL) TO VISIBLE
        grossLbl.setVisible(true);
        grossTF.setVisible(true);
        prsilbl.setVisible(true);
        prsiTF.setVisible(true);

        usclbl.setVisible(true);
        uscTF.setVisible(true);

        netpaylbl.setVisible(true);
        netpayTF.setVisible(true);
        paylbl.setVisible(true);
        payTF.setVisible(true);

        for (int i = 0; i < aList.size(); i++) {
            // USE EMPLOYEE DETAILS AS A POLYORPHISM METHOD TO PRINT EMPLOYEED DETAILS LIKE  FIRSTNAME,SURNAME ,DOB,ID, PPS AND ADDRESS

            // PRINT FIANCIAL DETAILS USING AlIST 
            JOptionPane.showMessageDialog(null, "employees details:    " + "\n" + aList.get(i).employeedetails() + "" + "\n gross" + aList.get(i).gross() + "" + "\n taxablePay" + aList.get(i).taxablePay() + "" + "\n prsi" + aList.get(i).prsi() + "" + "\n usc" + aList.get(i).usc() + "" + "\n pay" + aList.get(i).pay() + "" + "\n netpay" + aList.get(i).netpay());
            if (aList.get(i).gross() == 0.0 || aList.get(i).taxablePay() == 0.0 || aList.get(i).prsi() == 0.0) {// IF GROOS, PRSI EQUAL TO ZERO MEANS THE FIANCIAL DETAILS IN NOT ENTERED BY THE USER 
                JOptionPane.showMessageDialog(null, " hello, this employee finacial details are empty" + "" + "\n   please enter financial details ");
            }

        }
    }//GEN-LAST:event_calculateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        grossLbl.setVisible(false);
        grossTF.setVisible(false);
        prsilbl.setVisible(false);
        prsiTF.setVisible(false);

        usclbl.setVisible(false);
        uscTF.setVisible(false);

        netpaylbl.setVisible(false);
        netpayTF.setVisible(false);
        paylbl.setVisible(false);
        payTF.setVisible(false);

        p = new payrol(); // CREATE AN INSTANCEC OF PAYROL CLASS
        // GET TEXT FROM TEXT FIELD
        firstname = firstname1TF.getText();
        surname = surname1TF.getText();
        id = id1TF.getText();
        dob = dob1TF.getText();
        ppsnumber = ppsnumber1TF.getText();
        address = addressTF.getText();

        hours = Double.parseDouble(hoursTF.getText());
        rate = Double.parseDouble(rateTF.getText());
        taxCredit = Double.parseDouble(taxCreditTF.getText());
        healthInsurance = Double.parseDouble(healthInsuranceTF.getText());
        unionSubs = Double.parseDouble(unionSubsTF.getText());
        overTime = Double.parseDouble(overtimeTF.getText());
        // PASS VALUES OF  VARIABELS  TO INSTACE OF CLASS P
        p.setFirstname(firstname);
        p.setSurname(surname);
        p.setId(id);
        p.setPpsnumber(ppsnumber);
        p.setDob(dob);
        p.setAddress(address);
        p.setHours(hours);
        p.setRate(rate);
        p.setOverTime(overTime);
        //   p.setTaxablePay(taxCredit);
        p.setUsc(usc);
        p.setTaxCredit(taxCredit);
        p.setUnionSubs(unionSubs);
        p.setHealthInsurance(healthInsurance);

        aList.add(p); // ADD ALL VALUES TO ARRAYLIST

        System.out.println("alist: " + aList.toString());// used for testing persposes
        writeToFile();// instead of creating another add button we simpply call the wrIte to file method inside add btn
    }//GEN-LAST:event_addActionPerformed

    private void unionSubsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unionSubsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unionSubsTFActionPerformed

    private void viewAddedDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddedDetailsActionPerformed
        for (int i = 0; i < aList.size(); i++) {
            // System.out.println("printing: "+aList.get(i));
            JOptionPane.showMessageDialog(null, aList.get(i).employeedetails());// use polymorphism to print employees details (firstname,surname,id,ppn,dob,address)

        }
    }//GEN-LAST:event_viewAddedDetailsActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // when user cliks clear button , all following text field will be cleared from diplaying
        firstname1TF.setText("");
        surname1TF.setText("");
        id1TF.setText("");
        surname1TF.setText("");
        dob1TF.setText("");
        ppsnumber1TF.setText("");
        addressTF.setText("");
        hoursTF.setText("");
        rateTF.setText("");
        uscTF.setText("");
        prsiTF.setText("");
        payTF.setText("");
        grossTF.setText("");
        healthInsuranceTF.setText("");
        taxCreditTF.setText("");
        netpayTF.setText("");
        overtimeTF.setText("");
        unionSubsTF.setText("");

        grossLbl.setVisible(false);
        grossTF.setVisible(false);
        prsilbl.setVisible(false);
        prsiTF.setVisible(false);

        usclbl.setVisible(false);
        uscTF.setVisible(false);

        netpaylbl.setVisible(false);
        netpayTF.setVisible(false);
        paylbl.setVisible(false);
        payTF.setVisible(false);

    }//GEN-LAST:event_ClearActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // this button provide information and help for user
        JOptionPane.showMessageDialog(null, " Please dont add empty values and try to fell all text field with proper values, if empty string acured log out and add details to all text field before clickig add button , thank you :)");
    }//GEN-LAST:event_helpActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String search = JOptionPane.showInputDialog("please enter employee name ");
        for (int i = 0; i < aList.size(); i++) {
            if (search.equalsIgnoreCase(aList.get(i).getFirstname())) {
                JOptionPane.showMessageDialog(null, "employees details:    " + "\n" + aList.get(i).employeedetails() + "" + "\n gross" + aList.get(i).gross() + "" + "\n taxablePay" + aList.get(i).taxablePay() + "" + "\n prsi" + aList.get(i).prsi() + "" + "\n usc" + aList.get(i).usc() + "" + "\n pay" + aList.get(i).pay() + "" + "\n netpay" + aList.get(i).netpay());
            }

        }
    }//GEN-LAST:event_searchActionPerformed

    private void viewcalculationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcalculationsActionPerformed
         JOptionPane.showMessageDialog(null, "Standard rates and thresholds of USC for 2018 " + "\n" + "2018                         rate" + "\n" + "First €12,012                0.5%" + "\n" + "Next €7,360                2%" + "\n" + "Next €50,672                4.75%");
        JOptionPane.showMessageDialog(null, "gross= rate*hours");
        JOptionPane.showMessageDialog(null, "taxablePay= gross+overTime");
        JOptionPane.showMessageDialog(null, "PRSI= taxablePay*0.04");
        JOptionPane.showMessageDialog(null, "if  taxablePay<=650:" + "\n"
                + "   pay= taxablePay*0.2  " + "\n"
                + "  if taxablePay>650 :" + "\n "
                + "pay= ((taxablePay-650)*0.4)+130 ");

    }//GEN-LAST:event_viewcalculationsActionPerformed

    private void ppsnumber1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppsnumber1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppsnumber1TFActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
         dispose(); //quit teh application
    }//GEN-LAST:event_logoutActionPerformed
public void writeToFile() {
        try {
            File a = new File("output.dat");//declare and create file object called output.dat used to write employees details
            FileOutputStream b = new FileOutputStream(a);//
            ObjectOutputStream c = new ObjectOutputStream(b);
            // write the object
            c.writeObject(aList);//log declared earlier
            //close the output stream
            c.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    public void readFromFile() {
        try {
            File a = new File("output.dat");//declare and create file object called output.dat used to read employees details
            FileInputStream b = new FileInputStream(a);
            ObjectInputStream c = new ObjectInputStream(b);
            // read the object from the file  array of object here called Log
            // convert prob   > cast it to remind it is a employee
            aList = (ArrayList<hr>) c.readObject();
            c.close();

        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payrolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payrolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payrolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payrolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payrolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton add;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField dob1TF;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField firstname1TF;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JLabel grossLbl;
    private javax.swing.JTextField grossTF;
    private javax.swing.JLabel healthInsuranceLbl;
    private javax.swing.JTextField healthInsuranceTF;
    private javax.swing.JButton help;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JTextField id1TF;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JTextField netpayTF;
    private javax.swing.JLabel netpaylbl;
    private javax.swing.JLabel overtimeLbl;
    private javax.swing.JTextField overtimeTF;
    private javax.swing.JTextField payTF;
    private javax.swing.JLabel paylbl;
    private javax.swing.JTextField ppsnumber1TF;
    private javax.swing.JLabel ppsnumberLbl;
    private javax.swing.JTextField prsiTF;
    private javax.swing.JLabel prsilbl;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTF;
    private javax.swing.JButton search;
    private javax.swing.JTextField surname1TF;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JLabel taxCreditLbl;
    private javax.swing.JTextField taxCreditTF;
    private javax.swing.JTextField unionSubsTF;
    private javax.swing.JTextField uscTF;
    private javax.swing.JLabel usclbl;
    private javax.swing.JButton viewAddedDetails;
    private javax.swing.JButton viewcalculations;
    // End of variables declaration//GEN-END:variables
}
