/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moduleapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17448556
 */
public class ModuleGUI extends javax.swing.JFrame {
        Module m;
        ArrayList <Module> modules = new ArrayList();
        String name;
        String lecturer;
        String date;
        String time;
        String tutorial1;
        String tutorial2;
        String labtime;
        String labAssistant;

    /**
     * Creates new form ModuleGUI
     */
    public ModuleGUI() {
        initComponents();
        tutorial1Lbl.setVisible(false);
        tutorial1Txt.setVisible(false);
        tutorial2Lbl.setVisible(false);
        tutorial2Txt.setVisible(false);
        labTimeLbl.setVisible(false);
        labAssistantLbl.setVisible(false);
        labTimeTxt.setVisible(false);
        labAssistantTxt.setVisible(false);
        
        readFromFile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleTitleLbl = new javax.swing.JLabel();
        moduleLbl = new javax.swing.JLabel();
        lecturerLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        moduleTxt = new javax.swing.JTextField();
        lecturerTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        timeTxt = new javax.swing.JTextField();
        tutorial1Lbl = new javax.swing.JLabel();
        tutorial2Lbl = new javax.swing.JLabel();
        labAssistantLbl = new javax.swing.JLabel();
        labTimeLbl = new javax.swing.JLabel();
        tutorial1Txt = new javax.swing.JTextField();
        tutorial2Txt = new javax.swing.JTextField();
        labAssistantTxt = new javax.swing.JTextField();
        labTimeTxt = new javax.swing.JTextField();
        addModuleBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        businessBtn = new javax.swing.JButton();
        technicalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moduleTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moduleTitleLbl.setText("Module Application");

        moduleLbl.setText("Module Name");

        lecturerLbl.setText("Lecturer Name");

        dateLbl.setText("Date");

        timeLbl.setText("Time");

        moduleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleTxtActionPerformed(evt);
            }
        });

        tutorial1Lbl.setText("Tutorial 1");

        tutorial2Lbl.setText("Tutorial 2");

        labAssistantLbl.setText("Lab Assistant");

        labTimeLbl.setText("Lab Time");

        addModuleBtn.setText("Add Module");
        addModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display Modules");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search for Modules");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Modules");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        businessBtn.setText("Business Module");
        businessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessBtnActionPerformed(evt);
            }
        });

        technicalBtn.setText("Technical Module");
        technicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(moduleTitleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moduleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecturerLbl)
                                    .addComponent(dateLbl)
                                    .addComponent(timeLbl)
                                    .addComponent(tutorial1Lbl)
                                    .addComponent(tutorial2Lbl)
                                    .addComponent(labAssistantLbl)
                                    .addComponent(labTimeLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecturerTxt)
                                    .addComponent(dateTxt)
                                    .addComponent(timeTxt)
                                    .addComponent(tutorial1Txt)
                                    .addComponent(tutorial2Txt)
                                    .addComponent(labAssistantTxt)
                                    .addComponent(labTimeTxt))))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addModuleBtn)
                            .addComponent(displayBtn)
                            .addComponent(searchBtn)
                            .addComponent(deleteBtn)
                            .addComponent(businessBtn)
                            .addComponent(technicalBtn))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduleTitleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moduleLbl)
                    .addComponent(moduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addModuleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lecturerLbl)
                    .addComponent(lecturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLbl)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLbl)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tutorial1Lbl)
                    .addComponent(tutorial1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businessBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tutorial2Lbl)
                    .addComponent(tutorial2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technicalBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labAssistantLbl)
                    .addComponent(labAssistantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTimeLbl)
                    .addComponent(labTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moduleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleTxtActionPerformed

    private void addModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleBtnActionPerformed
        // TODO add your handling code here:
        if (m instanceof Business){
            m.setName(moduleTxt.getText());
            m.setLecturer(lecturerTxt.getText());
            m.setDate(dateTxt.getText());
            m.setTime(timeTxt.getText());
            ((Business)(m)).setTutorial1(tutorial1Txt.getText());
            ((Business)(m)).setTutorial2(tutorial2Txt.getText());
            
            modules.add(m);
        }
        if (m instanceof Technical){
            m.setName(moduleTxt.getText());
            m.setLecturer(lecturerTxt.getText());
            m.setDate(dateTxt.getText());
            m.setTime(timeTxt.getText());
            ((Technical)(m)).setLabTime(labTimeTxt.getText());
            ((Technical)(m)).setLabAssistant(labAssistantTxt.getText());
            
            modules.add(m);
        }
        writeToFile();
        
        
    }//GEN-LAST:event_addModuleBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < modules.size(); i++) {
            JOptionPane.showMessageDialog(null, modules.get(i).printModule());
        }
    }//GEN-LAST:event_displayBtnActionPerformed
        public void writeToFile(){
            try{
                File f  = new File("modules.dat");
                FileOutputStream fStream = new FileOutputStream(f);
                ObjectOutputStream oStream = new ObjectOutputStream(fStream);
                oStream.writeObject(modules);
                oStream.close();
            }
            catch(IOException e){
                System.out.println(e);
            }
        
        }
        public void readFromFile(){
                try{
                        File f = new File("modules.dat");
                        FileInputStream fStream = new FileInputStream(f);
                        ObjectInputStream oStream = new ObjectInputStream(fStream);
                        modules = (ArrayList<Module>)oStream.readObject();
                        oStream.close();
                        
                }
                        
                        
                catch(IOException | ClassNotFoundException ex){
                        System.out.println(ex);
                        }
        }
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void businessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessBtnActionPerformed
        // TODO add your handling code here:
        tutorial1Lbl.setVisible(true);
        tutorial1Txt.setVisible(true);
        tutorial2Lbl.setVisible(true);
        tutorial2Txt.setVisible(true);
         labTimeLbl.setVisible(false);
        labAssistantLbl.setVisible(false);
        labTimeTxt.setVisible(false);
        labAssistantTxt.setVisible(false);
        
        m = new Business();
        
    }//GEN-LAST:event_businessBtnActionPerformed

    private void technicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicalBtnActionPerformed
        // TODO add your handling code here:
         labTimeLbl.setVisible(true);
        labAssistantLbl.setVisible(true);
        labTimeTxt.setVisible(true);
        labAssistantTxt.setVisible(true);
        tutorial1Lbl.setVisible(false);
        tutorial1Txt.setVisible(false);
        tutorial2Lbl.setVisible(false);
        tutorial2Txt.setVisible(false);
        
        m = new Technical();
    }//GEN-LAST:event_technicalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModuleBtn;
    private javax.swing.JButton businessBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel labAssistantLbl;
    private javax.swing.JTextField labAssistantTxt;
    private javax.swing.JLabel labTimeLbl;
    private javax.swing.JTextField labTimeTxt;
    private javax.swing.JLabel lecturerLbl;
    private javax.swing.JTextField lecturerTxt;
    private javax.swing.JLabel moduleLbl;
    private javax.swing.JLabel moduleTitleLbl;
    private javax.swing.JTextField moduleTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton technicalBtn;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JLabel tutorial1Lbl;
    private javax.swing.JTextField tutorial1Txt;
    private javax.swing.JLabel tutorial2Lbl;
    private javax.swing.JTextField tutorial2Txt;
    // End of variables declaration//GEN-END:variables
}
