/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17448556
 */
public class bankGUI extends javax.swing.JFrame {

    /**
     * Creates new form bankGUI
     */
    bankAccounts b;
    String accountName;
    double accountNumber;
    double balance;
    double atmCharge;
    double interestRate;
    ArrayList <bankAccounts>accounts = new ArrayList();
    public bankGUI() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        accountNumberLbl = new javax.swing.JLabel();
        balanceLbl = new javax.swing.JLabel();
        atmChargeLbl = new javax.swing.JLabel();
        rateLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        accountNumberTxt = new javax.swing.JTextField();
        balanceTxt = new javax.swing.JTextField();
        atmChargeTxt = new javax.swing.JTextField();
        rateTxt = new javax.swing.JTextField();
        currentBtn = new javax.swing.JButton();
        savingBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLbl.setText("Bank Application");

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLbl.setText("Name");

        accountNumberLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accountNumberLbl.setText("Account number");

        balanceLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        balanceLbl.setText("Balance");

        atmChargeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atmChargeLbl.setText("Atm Charge");

        rateLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rateLbl.setText("Interest Rate");

        currentBtn.setText("Current Account");
        currentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentBtnActionPerformed(evt);
            }
        });

        savingBtn.setText("Saving Account");
        savingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountNumberLbl)
                            .addComponent(nameLbl)
                            .addComponent(balanceLbl)
                            .addComponent(atmChargeLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addBtn)
                                .addComponent(rateLbl)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(displayBtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(balanceTxt)
                                        .addComponent(atmChargeTxt)
                                        .addComponent(rateTxt)
                                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(accountNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 107, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savingBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberLbl)
                    .addComponent(accountNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingBtn))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLbl)
                    .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atmChargeLbl)
                    .addComponent(atmChargeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLbl)
                    .addComponent(rateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(displayBtn))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        bankAccounts b = new bankAccounts();
        accountName = nameTxt.getText();
        accountNumber = Double.parseDouble(accountNumberTxt.getText());
        balance = Double.parseDouble(balanceTxt.getText());
        
        b.setAccountName(accountName);
        b.setAccountNumber(accountNumber);
        b.setBalance(balance);
        accounts.add(b);
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
       for (int i=0; i < accounts.size(); i++){
            JOptionPane.showMessageDialog(null, "Here are the details " + accounts.get(i).accountDetails());
        } 
    }//GEN-LAST:event_displayBtnActionPerformed

    private void currentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentBtnActionPerformed
        // TODO add your handling code here:
        rateLbl.setVisible(false);
        rateTxt.setVisible(false);
        atmChargeLbl.setVisible(true);
        atmChargeTxt.setVisible(true);
    }//GEN-LAST:event_currentBtnActionPerformed

    private void savingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingBtnActionPerformed
        // TODO add your handling code here:
        rateLbl.setVisible(true);
        rateTxt.setVisible(true);
        atmChargeLbl.setVisible(false);
        atmChargeTxt.setVisible(false);
    }//GEN-LAST:event_savingBtnActionPerformed
     public void readFromFile(){
        try{
        File f = new File("output.dat");
        FileInputStream fStream = new FileInputStream(f);
        ObjectInputStream oStream = new ObjectInputStream(fStream);
       
    }
        catch(IOException e)
        {
        System.out.println(e);
        }      
    };
    public void writeToFile()
    {
        try{
        File f = new File("output.dat");
        FileOutputStream fStream = new FileOutputStream(f);
        ObjectOutputStream oStream = new ObjectOutputStream(fStream);
        
    }
        catch(IOException e)
        {
        System.out.println(e);
        }
        
    
        
                
    };
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberLbl;
    private javax.swing.JTextField accountNumberTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel atmChargeLbl;
    private javax.swing.JTextField atmChargeTxt;
    private javax.swing.JLabel balanceLbl;
    private javax.swing.JTextField balanceTxt;
    private javax.swing.JButton currentBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTxt;
    private javax.swing.JButton savingBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
